name: awesome_datepicker
description: A sleek widget that lets your users input dates using a color picker!
version: 0.1.1
homepage: https://adityarajput.co/awesome_datepicker/

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
