name: build and push example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            aws-region: ap-south-1
    
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3

      - name: Build example
        run: |
          cd example
          flutter build web

      - name: Copy files
        run: |
          docker run --name example example
          docker cp example:/app/example/build/web ./build

      - name: Push files
        run: aws s3 sync ./build/ $AWS_S3_BUCKET --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        env:
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
